{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "capiovh.fullname" . }}-allow-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "capiovh.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      control-plane: controller-manager
      {{- include "capiovh.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              metrics: enabled
      ports:
        - port: 8443
          protocol: TCP
{{- end }}
